# Generated by Django 2.1.5 on 2019-03-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190315_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
