# Generated by Django 2.1.5 on 2019-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190412_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='health_problem',
            field=models.TextField(default='nothing', max_length=200),
        ),
    ]
