# Generated by Django 2.1.7 on 2019-03-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eprescription',
            old_name='after_breakfrist',
            new_name='after_breakfirst',
        ),
    ]
