# Generated by Django 2.1.7 on 2019-04-05 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20190404_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='eprescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.TextField()),
                ('comment', models.CharField(max_length=250, null=True)),
                ('test', models.CharField(max_length=250, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Patient_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Patient')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
