# Generated by Django 2.1.5 on 2019-04-11 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190404_1936'),
        ('service', '0002_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eprescriptions',
            name='Patient_name',
        ),
        migrations.AddField(
            model_name='eprescriptions',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eprescription', to='users.Patient'),
        ),
        migrations.AlterField(
            model_name='eprescriptions',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eprescription', to=settings.AUTH_USER_MODEL),
        ),
    ]
