# Generated by Django 2.1.5 on 2019-04-11 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190404_1936'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_auto_20190411_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eprescriptions',
            new_name='Prescription',
        ),
    ]
