# Generated by Django 2.1.5 on 2019-04-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190411_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
