# Generated by Django 2.1.5 on 2019-04-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190411_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='test',
        ),
    ]
