# Generated by Django 2.1.7 on 2019-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20190416_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_Record', models.CharField(choices=[('Prescription', 'Prescription'), ('Bloodtest', 'Bloodtest'), ('X_Ray', 'X-Ray'), ('AIDS_Test', 'AIDS Test'), ('Aldosterone_in_Urine', 'Aldosterone in Urine'), ('Eye_Angiogram', 'Eye Angiogram'), ('Electroencephalogram ', 'Electroencephalogram '), ('ECT', 'ECT')], max_length=15, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
